spring.application.name=question_micro

spring.datasource.url=jdbc:postgresql://localhost:5432/questions
spring.datasource.username=postgres
spring.datasource.password=assem123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true